spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jakarta_persistence_validation_mode: none
    open-in-view: false
  security:
    oauth2:
      client:
        provider:
          azure:
            # Azure AD Issuer URI
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
            # Authorization Endpoint
            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/authorize
            # Token Endpoint
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
            # JWK Set URI
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
            # User Info Endpoint
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            # Username Attribute
            user-name-attribute: name
        registration:
          azure:
            provider: azure
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/secure/auth"      
            scope:
            - openid
            - email
            - profile
  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    context-path: /publication


aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucketName: ${AWS_S3_BUCKET_NAME}

# Group mapping

jwt:
  authorization:
    roles:
      SFPCCAR:
        group-id: "b6e5f014-ddfe-471a-9980-d8bae9340c6b"
        allowed: true
        exercises:
          - CCAR
          - PARALLEL_CCAR
      SFPCECL:
        group-id: "6b17398b-c03a-43dd-8f4a-bd18bbff8bd2"
        allowed: true
        exercises:
          - CECL
          - PARALLEL_CECL
      SFPECB:
        group-id: "04b60881-2964-4d24-8b69-6b8cf7e0c444"
        allowed: true
        exercises:
          - ECB
          - PARALLEL_ECB
      SFPICAAP:
        group-id: "6e1abf19-700e-4a4e-9c2a-f8b65aace45f"
        allowed: true
        exercises:
          - ICAAP
          - PARALLEL_ICAAP
